### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by SteveBehm** [adrienbrignon/mkdocs-exporter#23]
Hello

I saw your recent update to the plugin and have been working to try to update my yml file on my end in order to use the new version.

I have created a dockerfile to create my documentation site that uses mkdocs mkdocs-material and mkdocs-exporter. This I haven't changed as it what working with the most recent release of your plugin.

However now, after updating the my mkdocs.yml file according to your documentation I am getting a runtime error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 268, in serve_command
    serve.serve(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 85, in serve
    builder(config)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 347, in build
    config.plugins.on_post_build(config=config)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 602, in on_post_build
    return self.run_event('post_build', config=config)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 568, in run_event
    result = method(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs_exporter/formats/pdf/plugin.py", line 150, in _on_post_build_1
    self.loop.run_until_complete(asyncio.gather(*concurrently(self.tasks, max(1, self.config.concurrency or 1))))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mkdocs_exporter/helpers.py", line 29, in limit
    return await asyncio.create_task(coroutine)
  File "/usr/local/lib/python3.9/site-packages/mkdocs_exporter/formats/pdf/plugin.py", line 128, in render
    pdf, pages = await self.renderer.render(html)
  File "/usr/local/lib/python3.9/site-packages/mkdocs_exporter/formats/pdf/renderer.py", line 85, in render
    await self.browser.launch()
  File "/usr/local/lib/python3.9/site-packages/mkdocs_exporter/formats/pdf/browser.py", line 55, in launch
    async with self.lock:
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 120, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-19' coro=<Plugin.on_post_page.<locals>.render() running at /usr/local/lib/python3.9/site-packages/mkdocs_exporter/formats/pdf/plugin.py:128> cb=[<TaskWakeupMethWrapper object at 0xffffa5f0a2e0>()]> got Future <Future pending> attached to a different loop
```

Here is the yml section I updated:
```
plugins:
  - search
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PD_ENABLED, true]
          concurrency: 16
          stylesheets:
            - resources/stylesheets/pdf.scss
          browser:
            debug: false
            headless: true
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
```
Is it possible that the error is being caused by something on your end? Perhaps the python package has not been updated yet or something?

**Comment by adrienbrignon** [comment]
Feel free to open another one if you encounter any problems.
