### ISSUE TITLE
Timeout during page.go_to(), expose as option

### ISSUE THREAD

**Issue by buti1021** [adrienbrignon/mkdocs-exporter#30]
Hey @adrienbrignon, 
thank you for this plugin! 

We are running into the default playwright timeout of 30s here:https://github.com/adrienbrignon/mkdocs-exporter/blob/master/mkdocs_exporter%2Fformats%2Fpdf%2Fbrowser.py#L99, increasing the timeout works, would you mind providing this as an option?
Probably shouldn't be reusing the timeout variable that is being used in Line #100?

```
Traceback (most recent call last):

543 File "/usr/local/bin/mkdocs", line 8, in <module>

544 sys.exit(cli())

545 File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__

546 return self.main(*args, **kwargs)

547 File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main

548 rv = self.invoke(ctx)

549 File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke

550 return _process_result(sub_ctx.command.invoke(sub_ctx))

551 File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke

552 return ctx.invoke(self.callback, **ctx.params)

553 File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke

554 return __callback(*args, **kwargs)

555 File "/usr/local/lib/python3.10/dist-packages/mkdocs/__main__.py", line 284, in build_command

556 build.build(cfg, dirty=not clean)

557 File "/usr/local/lib/python3.10/dist-packages/mkdocs/commands/build.py", line 347, in build

558 config.plugins.on_post_build(config=config)

559 File "/usr/local/lib/python3.10/dist-packages/mkdocs/plugins.py", line 602, in on_post_build

560 return self.run_event('post_build', config=config)

561 File "/usr/local/lib/python3.10/dist-packages/mkdocs/plugins.py", line 568, in run_event

562 result = method(**kwargs)

563 File "/usr/local/lib/python3.10/dist-packages/mkdocs_exporter/formats/pdf/plugin.py", line 154, in _on_post_build_1

564 self.loop.run_until_complete(asyncio.gather(*concurrently(self.tasks, max(1, self.config.concurrency or 1))))

565 File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete

566 return future.result()

567 File "/usr/local/lib/python3.10/dist-packages/mkdocs_exporter/helpers.py", line 29, in limit

568 return await asyncio.create_task(coroutine)

569 File "/usr/local/lib/python3.10/dist-packages/mkdocs_exporter/formats/pdf/plugin.py", line 135, in render

570 pdf, pages = await self.renderer.render(html)

571 File "/usr/local/lib/python3.10/dist-packages/mkdocs_exporter/formats/pdf/renderer.py", line 91, in render

572 return await self.browser.print(html)

573 File "/usr/local/lib/python3.10/dist-packages/mkdocs_exporter/formats/pdf/browser.py", line 99, in print

574 await context.goto('file://' + file.name, wait_until='networkidle')

575 File "/usr/local/lib/python3.10/dist-packages/playwright/async_api/_generated.py", line 8818, in goto

576 await self._impl_obj.goto(

577 File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_page.py", line 524, in goto

578 return await self._main_frame.goto(**locals_to_params(locals()))

579 File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_frame.py", line 145, in goto

580 await self._channel.send("goto", locals_to_params(locals()))

581 File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 59, in send

582 return await self._connection.wrap_api_call(

583 File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call

584 raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None

585playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.

586Call log:

587navigating to "file:///tmp/tmpaceq8jaw.html", waiting until "networkidle"
```

Best,

Buti

**Comment by adrienbrignon** [comment]
Hello @buti1021,

Nice catch!
I've just released the version https://github.com/adrienbrignon/mkdocs-exporter/releases/tag/v6.1.1 that should fixes the issue.

Thanks
